template:
  cluster_template:
    name: murano_tests
    network:
      neutron-dvr: false
      neutron-l2-pop: false
      neutron-l3-ha: false
      neutron-qos: true
      provider: neutron
      pubip-to-all: false
      segment-type: tun
    nodes:
      - count: 3
        roles: [controller]
      - count: 1
        roles: [compute, ceph-osd]

    release: ubuntu
    settings:
      components:
        ceilometer: false
        ironic: false
        murano: true
        sahara: false
      storages:
        ephemeral-ceph: false
        image-ceph: true
        rados-ceph: true
        volume-ceph: true
        volume-lvm: false
        replica-ceph: 1

  devops_settings:
    env_name: !os_env ENV_NAME

    aliases:
      dynamic_address_pool:
       - &pool_default !os_env POOL_DEFAULT, 10.109.0.0/16:24

      default_interface_model:
       - &interface_model !os_env INTERFACE_MODEL, e1000

      rack-01-slave-interfaces: &rack-01-slave-interfaces
       - label: eth0
         l2_network_device: admin
         interface_model: *interface_model
       - label: eth1
         l2_network_device: openstack_br
         interface_model: *interface_model

      rack-01-slave-network_config: &rack-01-slave-network_config
        eth0:
          networks:
           - fuelweb_admin
        eth1:
          networks:
           - public
           - management
           - storage
           - private

      rack-01-controller-node-params: &controller-node-params
        boot: [network, hd]
        interfaces: *rack-01-slave-interfaces
        memory: 12288
        network_config: *rack-01-slave-network_config
        vcpu: 2
        volumes:
        - {capacity: 80, format: qcow2, name: system}
        - {capacity: 80, format: qcow2, name: cinder}
        - {capacity: 80, format: qcow2, name: swift}

    address_pools:
    # Network pools used by the environment
      fuelweb_admin-pool01:
        net: *pool_default
        params: {tag: 100}
      public-pool01:
        net: *pool_default
        params: {tag: 823}
      management-pool01:
        net: *pool_default
        params: {tag: 101}
      storage-pool01:
        net: *pool_default
        params: {tag: 102}
      private-pool01:
        net: *pool_default
        params: {tag: 103}
      fuelweb_admin-pool02:
        net: *pool_default
        params: {tag: 100}
      public-pool02:
        net: *pool_default
        params: {tag: 823}
      management-pool02:
        net: *pool_default
        params: {tag: 101}
      storage-pool02:
        net: *pool_default
        params: {tag: 102}
      private-pool02:
        net: *pool_default
        params: {tag: 103}

    groups:
     - name: default
       driver:
         name: devops.driver.libvirt
         params:
           connection_string: !os_env CONNECTION_STRING, qemu:///system
           storage_pool_name: !os_env STORAGE_POOL_NAME, default
           stp: False
           hpet: False
           use_host_cpu: !os_env DRIVER_USE_HOST_CPU, true

       network_pools:
         # Address pools for OpenStack networks.
         # Actual names should be used for keys
         # (the same as in Nailgun, for example)

         fuelweb_admin: fuelweb_admin-pool01
         public: public-pool01
         management: management-pool01
         storage: storage-pool01
         private: private-pool01

       l2_network_devices:  # Libvirt bridges. It is *NOT* Nailgun networks
         admin:
           address_pool: fuelweb_admin-pool01
           dhcp: false
           forward:
             mode: nat
           parent_iface:
             l2_net_dev: openstack_br
             tag: 100

         openstack_br:
           vlan_ifaces:
             - 100
             - 823
             - 101
             - 102
             - 103
           parent_iface:
             phys_dev: !os_env BAREMETAL_ADMIN_IFACE, eth1

         public:
           address_pool: public-pool01
           dhcp: false
           forward:
             mode: nat
           parent_iface:
             l2_net_dev: openstack_br
             tag: 823

         management:
           address_pool: management-pool01
           dhcp: false
           parent_iface:
             l2_net_dev: openstack_br
             tag: 101

         storage:
           address_pool: storage-pool01
           dhcp: false
           parent_iface:
             l2_net_dev: openstack_br
             tag: 102

         private:
           address_pool: private-pool01
           dhcp: false
           parent_iface:
             l2_net_dev: openstack_br
             tag: 103

       nodes:
        - name: admin        # Custom name of VM for Fuel admin node
          role: fuel_master  # Fixed role for Fuel master node properties
          params:
            vcpu: !os_env ADMIN_NODE_CPU, 2
            memory: !os_env ADMIN_NODE_MEMORY, 4096
            boot:
              - hd
              - cdrom  # for boot from usb - without 'cdrom'
            volumes:
             - name: system
               capacity: !os_env ADMIN_NODE_VOLUME_SIZE, 80
               format: qcow2
             - name: iso
               source_image: !os_env ISO_PATH    # if 'source_image' set, then volume capacity is calculated from it's size
               format: raw
               device: cdrom   # for boot from usb - 'disk'
               bus: ide        # for boot from usb - 'usb'
            interfaces:
             - label: eth0
               l2_network_device: admin    # Libvirt bridge name. It is *NOT* a Nailgun network
               interface_model: *interface_model
            network_config:
              eth0:
                networks:
                 - fuelweb_admin

        - name: slave-01
          params: *controller-node-params
          role: fuel_slave
        - name: slave-02
          params: *controller-node-params
          role: fuel_slave
        - name: slave-03
          params: *controller-node-params
          role: fuel_slave

     - name: baremetal-rack01
       driver:
         name: devops.driver.baremetal
          # Slave nodes

       network_pools:  # Address pools for OpenStack networks.
         # Actual names should be used for keys
         # (the same as in Nailgun, for example)

         fuelweb_admin: fuelweb_admin-pool02
         public: public-pool02
         management: management-pool02
         storage: storage-pool02
         private: private-pool02

       nodes:
        - name: slave-04  # Custom name of baremetal for Fuel slave node
          role: fuel_slave  # Fixed role for Fuel master node properties
          params:
            ipmi_user: !os_env MOSQA_IPMI_USER
            ipmi_password: !os_env MOSQA_IPMI_PASSWORD
            ipmi_previlegies: ADMINISTRATOR
            ipmi_host: cz7905-kvm.host-telecom.com
            ipmi_lan_interface: lanplus
            ipmi_port: 623

            # so, interfaces can be turn on in one or in a different switches.
            interfaces:
             - label: eth0
               mac_address: 0c:c4:7a:6d:3d:fc
             - label: eth1
               mac_address: 0c:c4:7a:6d:3d:fd
            network_config:
              eth0:
                networks:
                 - fuelweb_admin  ## OpenStack network, NOT switch name
              eth1:
                networks:
                 - public  ## OpenStack network, NOT switch name
                 - management  ## OpenStack network, NOT switch name
                 - storage  ## OpenStack network, NOT switch name
                 - private  ## OpenStack network, NOT switch name

  name: 3 Controller, 1 Compute+Ceph, Neutron, VLAN, Murano
  slaves: 4
