ISO_NAME=$(ls "$ISO_DIR")
export ENV_NAME="${ENV_PREFIX}${ISO_NAME}${ENV_SUFFIX}"
export ISO_PATH="$ISO_DIR/$ISO_NAME"
CONFIG_FOLDER=$(basename $(dirname $CONFIG_PATH))
CONFIG_FILE=$(basename $CONFIG_PATH)
CONFIG_NAME="${CONFIG_FILE%.*}"
export SNAPSHOT_NAME="$CONFIG_FOLDER"_"$CONFIG_NAME"

source $SNAPSHOT_RC_FILE
export EXTRA_DEB_REPOS
export EXTRA_RPM_REPOS
export UPDATE_FUEL_MIRROR
export UPDATE_MASTER
export SNAPSHOT_ID
